# Generated by Django 2.2.5 on 2021-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210322_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
