# Generated by Django 2.2.5 on 2021-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=40)),
                ('price0', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('type0', models.CharField(max_length=20)),
                ('size0', models.CharField(max_length=30)),
                ('desc0', models.CharField(max_length=200, null=True)),
                ('img0', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
