# Generated by Django 2.2.5 on 2021-05-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img0',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nameproduct',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price0',
            new_name='price',
        ),
    ]
